namespace Jobzy.Common
{
    using System.ComponentModel.DataAnnotations;

    public enum Country
    {
        [Display(Name = "Australia")] AU = 1,
        [Display(Name = "Austria")] AT = 2,
        [Display(Name = "Belgium")] BE = 3,
        [Display(Name = "Brazil")] BR = 4,
        [Display(Name = "Bulgaria")] BG = 5,
        [Display(Name = "Canada")] CA = 6,
        [Display(Name = "Cyprus")] CY = 7,
        [Display(Name = "Czechia")] CZ = 8,
        [Display(Name = "Denmark")] DK = 9,
        [Display(Name = "Estonia")] EE = 10,
        [Display(Name = "Finland")] FI = 11,
        [Display(Name = "France")] FR = 12,
        [Display(Name = "Germany")] DE = 13,
        [Display(Name = "Greece")] GR = 14,
        [Display(Name = "Hong Kong")] HK = 15,
        [Display(Name = "Hungary")] HU = 16,
        [Display(Name = "India")] IN = 17,
        [Display(Name = "Ireland")] IE = 18,
        [Display(Name = "Italy")] IT = 19,
        [Display(Name = "Japan")] JP = 20,
        [Display(Name = "Latvia")] LV = 21,
        [Display(Name = "Lithuania")] LT = 22,
        [Display(Name = "Luxembourg")] LU = 23,
        [Display(Name = "Malta")] MT = 24,
        [Display(Name = "Mexico")] MX = 25,
        [Display(Name = "Netherlands")] NL = 26,
        [Display(Name = "New Zealand")] NZ = 27,
        [Display(Name = "Norway")] NO = 28,
        [Display(Name = "Poland")] PL = 29,
        [Display(Name = "Portugal")] PT = 30,
        [Display(Name = "Romania")] RO = 31,
        [Display(Name = "Singapore")] SG = 32,
        [Display(Name = "Slovakia")] SK = 33,
        [Display(Name = "Slovenia")] SI = 34,
        [Display(Name = "Spain")] ES = 35,
        [Display(Name = "Swaziland")] SZ = 36,
        [Display(Name = "Sweden")] SE = 37,
        [Display(Name = "Switzerland")] CH = 38,
        [Display(Name = "United Kingdom of Great Britain")] GB = 39,
        [Display(Name = "United States of America")] US = 40,
    }
}
